-- =============================================================================
-- 为业务表与 Quartz 表补充 MySQL 表/字段注释（不改动已执行的 V1/V3，避免 checksum 冲突）
-- 查看：SHOW FULL COLUMNS FROM sys_user; 或 information_schema.COLUMNS.COLUMN_COMMENT
-- =============================================================================

-- ---------------------------------------------------------------------------
-- sys_user
-- ---------------------------------------------------------------------------
ALTER TABLE sys_user COMMENT = '系统用户表（JPA 写路径主表）';
ALTER TABLE sys_user
    MODIFY COLUMN id            BIGINT       NOT NULL COMMENT '主键ID',
    MODIFY COLUMN username      VARCHAR(64)  NOT NULL COMMENT '登录用户名（唯一）',
    MODIFY COLUMN password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希（BCrypt）',
    MODIFY COLUMN nickname      VARCHAR(64)  NOT NULL COMMENT '显示昵称',
    MODIFY COLUMN enabled       TINYINT(1)   NOT NULL DEFAULT 1 COMMENT '是否启用：1是 0否',
    MODIFY COLUMN deleted       INT          NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删 非0已删',
    MODIFY COLUMN created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    MODIFY COLUMN version       BIGINT       NOT NULL DEFAULT 0 COMMENT '乐观锁版本号';

-- ---------------------------------------------------------------------------
-- sys_role
-- ---------------------------------------------------------------------------
ALTER TABLE sys_role COMMENT = '系统角色表';
ALTER TABLE sys_role
    MODIFY COLUMN id         BIGINT       NOT NULL COMMENT '主键ID',
    MODIFY COLUMN code       VARCHAR(64)  NOT NULL COMMENT '角色编码（唯一，如 ADMIN）',
    MODIFY COLUMN name       VARCHAR(64)  NOT NULL COMMENT '角色名称',
    MODIFY COLUMN deleted    INT          NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删 非0已删',
    MODIFY COLUMN created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    MODIFY COLUMN version    BIGINT       NOT NULL DEFAULT 0 COMMENT '乐观锁版本号';

-- ---------------------------------------------------------------------------
-- sys_permission
-- ---------------------------------------------------------------------------
ALTER TABLE sys_permission COMMENT = '系统权限表';
ALTER TABLE sys_permission
    MODIFY COLUMN id         BIGINT        NOT NULL COMMENT '主键ID',
    MODIFY COLUMN code       VARCHAR(128)  NOT NULL COMMENT '权限编码（唯一，如 system:user:read）',
    MODIFY COLUMN name       VARCHAR(128)  NOT NULL COMMENT '权限名称',
    MODIFY COLUMN deleted    INT           NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删 非0已删',
    MODIFY COLUMN created_at DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    MODIFY COLUMN version    BIGINT        NOT NULL DEFAULT 0 COMMENT '乐观锁版本号';

-- ---------------------------------------------------------------------------
-- 关联表
-- ---------------------------------------------------------------------------
ALTER TABLE sys_user_role COMMENT = '用户-角色关联表';
ALTER TABLE sys_user_role
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID';

ALTER TABLE sys_role_permission COMMENT = '角色-权限关联表';
ALTER TABLE sys_role_permission
    MODIFY COLUMN role_id       BIGINT NOT NULL COMMENT '角色ID',
    MODIFY COLUMN permission_id BIGINT NOT NULL COMMENT '权限ID';

-- ---------------------------------------------------------------------------
-- demo_product
-- ---------------------------------------------------------------------------
ALTER TABLE demo_product COMMENT = '演示商品表（JPA 写 / MyBatis 复杂读）';
ALTER TABLE demo_product
    MODIFY COLUMN id          BIGINT       NOT NULL COMMENT '主键ID',
    MODIFY COLUMN sku         VARCHAR(64)  NOT NULL COMMENT '商品SKU（唯一）',
    MODIFY COLUMN name        VARCHAR(128) NOT NULL COMMENT '商品名称',
    MODIFY COLUMN category    VARCHAR(64)  NOT NULL COMMENT '商品分类',
    MODIFY COLUMN price_cents BIGINT       NOT NULL COMMENT '价格（分）',
    MODIFY COLUMN stock       INT          NOT NULL DEFAULT 0 COMMENT '库存数量',
    MODIFY COLUMN status      VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/INACTIVE 等',
    MODIFY COLUMN deleted     INT          NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删 非0已删',
    MODIFY COLUMN created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    MODIFY COLUMN version     BIGINT       NOT NULL DEFAULT 0 COMMENT '乐观锁版本号';

-- ---------------------------------------------------------------------------
-- Quartz JDBC 集群表（官方表结构 + 中文注释）
-- ---------------------------------------------------------------------------
ALTER TABLE QRTZ_JOB_DETAILS COMMENT = 'Quartz：Job 明细';
ALTER TABLE QRTZ_JOB_DETAILS
    MODIFY COLUMN SCHED_NAME        VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN JOB_NAME          VARCHAR(190) NOT NULL COMMENT 'Job 名称',
    MODIFY COLUMN JOB_GROUP         VARCHAR(190) NOT NULL COMMENT 'Job 分组',
    MODIFY COLUMN DESCRIPTION       VARCHAR(250) NULL COMMENT 'Job 描述',
    MODIFY COLUMN JOB_CLASS_NAME    VARCHAR(250) NOT NULL COMMENT 'Job 实现类全限定名',
    MODIFY COLUMN IS_DURABLE        VARCHAR(1)   NOT NULL COMMENT '是否持久化',
    MODIFY COLUMN IS_NONCONCURRENT  VARCHAR(1)   NOT NULL COMMENT '是否禁止并发执行',
    MODIFY COLUMN IS_UPDATE_DATA   VARCHAR(1)   NOT NULL COMMENT '是否更新 JobData',
    MODIFY COLUMN REQUESTS_RECOVERY VARCHAR(1)   NOT NULL COMMENT '故障后是否请求恢复',
    MODIFY COLUMN JOB_DATA          BLOB         NULL COMMENT 'Job 数据（序列化）';

ALTER TABLE QRTZ_TRIGGERS COMMENT = 'Quartz：Trigger 主表';
ALTER TABLE QRTZ_TRIGGERS
    MODIFY COLUMN SCHED_NAME     VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN TRIGGER_NAME   VARCHAR(190) NOT NULL COMMENT 'Trigger 名称',
    MODIFY COLUMN TRIGGER_GROUP  VARCHAR(190) NOT NULL COMMENT 'Trigger 分组',
    MODIFY COLUMN JOB_NAME       VARCHAR(190) NOT NULL COMMENT '关联 Job 名称',
    MODIFY COLUMN JOB_GROUP      VARCHAR(190) NOT NULL COMMENT '关联 Job 分组',
    MODIFY COLUMN DESCRIPTION    VARCHAR(250) NULL COMMENT 'Trigger 描述',
    MODIFY COLUMN NEXT_FIRE_TIME BIGINT       NULL COMMENT '下次触发时间（毫秒时间戳）',
    MODIFY COLUMN PREV_FIRE_TIME BIGINT       NULL COMMENT '上次触发时间（毫秒时间戳）',
    MODIFY COLUMN PRIORITY       INTEGER      NULL COMMENT '优先级',
    MODIFY COLUMN TRIGGER_STATE  VARCHAR(16)  NOT NULL COMMENT '状态：WAITING/ACQUIRED/PAUSED 等',
    MODIFY COLUMN TRIGGER_TYPE   VARCHAR(8)   NOT NULL COMMENT '类型：CRON/SIMPLE/BLOB 等',
    MODIFY COLUMN START_TIME     BIGINT       NOT NULL COMMENT '开始时间（毫秒时间戳）',
    MODIFY COLUMN END_TIME       BIGINT       NULL COMMENT '结束时间（毫秒时间戳）',
    MODIFY COLUMN CALENDAR_NAME  VARCHAR(190) NULL COMMENT '关联日历名称',
    MODIFY COLUMN MISFIRE_INSTR  SMALLINT     NULL COMMENT '错过触发处理策略',
    MODIFY COLUMN JOB_DATA       BLOB         NULL COMMENT 'Trigger 附带 Job 数据';

ALTER TABLE QRTZ_SIMPLE_TRIGGERS COMMENT = 'Quartz：Simple Trigger 扩展';
ALTER TABLE QRTZ_SIMPLE_TRIGGERS
    MODIFY COLUMN SCHED_NAME      VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN TRIGGER_NAME    VARCHAR(190) NOT NULL COMMENT 'Trigger 名称',
    MODIFY COLUMN TRIGGER_GROUP   VARCHAR(190) NOT NULL COMMENT 'Trigger 分组',
    MODIFY COLUMN REPEAT_COUNT    BIGINT       NOT NULL COMMENT '重复次数（-1 表示无限）',
    MODIFY COLUMN REPEAT_INTERVAL BIGINT       NOT NULL COMMENT '重复间隔（毫秒）',
    MODIFY COLUMN TIMES_TRIGGERED BIGINT       NOT NULL COMMENT '已触发次数';

ALTER TABLE QRTZ_CRON_TRIGGERS COMMENT = 'Quartz：Cron Trigger 扩展';
ALTER TABLE QRTZ_CRON_TRIGGERS
    MODIFY COLUMN SCHED_NAME      VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN TRIGGER_NAME    VARCHAR(190) NOT NULL COMMENT 'Trigger 名称',
    MODIFY COLUMN TRIGGER_GROUP   VARCHAR(190) NOT NULL COMMENT 'Trigger 分组',
    MODIFY COLUMN CRON_EXPRESSION VARCHAR(120) NOT NULL COMMENT 'Cron 表达式',
    MODIFY COLUMN TIME_ZONE_ID    VARCHAR(80)  NULL COMMENT '时区 ID';

ALTER TABLE QRTZ_SIMPROP_TRIGGERS COMMENT = 'Quartz：CalendarInterval/DailyTimeInterval 等属性 Trigger';
ALTER TABLE QRTZ_SIMPROP_TRIGGERS
    MODIFY COLUMN SCHED_NAME    VARCHAR(120)   NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN TRIGGER_NAME  VARCHAR(190)   NOT NULL COMMENT 'Trigger 名称',
    MODIFY COLUMN TRIGGER_GROUP VARCHAR(190)   NOT NULL COMMENT 'Trigger 分组',
    MODIFY COLUMN STR_PROP_1    VARCHAR(512)   NULL COMMENT '字符串属性1',
    MODIFY COLUMN STR_PROP_2    VARCHAR(512)   NULL COMMENT '字符串属性2',
    MODIFY COLUMN STR_PROP_3    VARCHAR(512)   NULL COMMENT '字符串属性3',
    MODIFY COLUMN INT_PROP_1    INT            NULL COMMENT '整型属性1',
    MODIFY COLUMN INT_PROP_2    INT            NULL COMMENT '整型属性2',
    MODIFY COLUMN LONG_PROP_1   BIGINT         NULL COMMENT '长整型属性1',
    MODIFY COLUMN LONG_PROP_2   BIGINT         NULL COMMENT '长整型属性2',
    MODIFY COLUMN DEC_PROP_1    NUMERIC(13, 4) NULL COMMENT '小数属性1',
    MODIFY COLUMN DEC_PROP_2    NUMERIC(13, 4) NULL COMMENT '小数属性2',
    MODIFY COLUMN BOOL_PROP_1   VARCHAR(1)     NULL COMMENT '布尔属性1',
    MODIFY COLUMN BOOL_PROP_2   VARCHAR(1)     NULL COMMENT '布尔属性2';

ALTER TABLE QRTZ_BLOB_TRIGGERS COMMENT = 'Quartz：Blob Trigger 扩展';
ALTER TABLE QRTZ_BLOB_TRIGGERS
    MODIFY COLUMN SCHED_NAME    VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN TRIGGER_NAME  VARCHAR(190) NOT NULL COMMENT 'Trigger 名称',
    MODIFY COLUMN TRIGGER_GROUP VARCHAR(190) NOT NULL COMMENT 'Trigger 分组',
    MODIFY COLUMN BLOB_DATA     BLOB         NULL COMMENT '序列化 Trigger 数据';

ALTER TABLE QRTZ_CALENDARS COMMENT = 'Quartz：日历（节假日等排除规则）';
ALTER TABLE QRTZ_CALENDARS
    MODIFY COLUMN SCHED_NAME    VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN CALENDAR_NAME VARCHAR(190) NOT NULL COMMENT '日历名称',
    MODIFY COLUMN CALENDAR      BLOB         NOT NULL COMMENT '序列化日历对象';

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS COMMENT = 'Quartz：已暂停的 Trigger 分组';
ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS
    MODIFY COLUMN SCHED_NAME    VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN TRIGGER_GROUP VARCHAR(190) NOT NULL COMMENT '已暂停的 Trigger 分组';

ALTER TABLE QRTZ_FIRED_TRIGGERS COMMENT = 'Quartz：正在执行/已获取的 Trigger';
ALTER TABLE QRTZ_FIRED_TRIGGERS
    MODIFY COLUMN SCHED_NAME        VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN ENTRY_ID          VARCHAR(95)  NOT NULL COMMENT '条目ID',
    MODIFY COLUMN TRIGGER_NAME      VARCHAR(190) NOT NULL COMMENT 'Trigger 名称',
    MODIFY COLUMN TRIGGER_GROUP     VARCHAR(190) NOT NULL COMMENT 'Trigger 分组',
    MODIFY COLUMN INSTANCE_NAME     VARCHAR(190) NOT NULL COMMENT '执行实例名',
    MODIFY COLUMN FIRED_TIME        BIGINT       NOT NULL COMMENT '实际触发时间（毫秒）',
    MODIFY COLUMN SCHED_TIME        BIGINT       NOT NULL COMMENT '计划触发时间（毫秒）',
    MODIFY COLUMN PRIORITY          INTEGER      NOT NULL COMMENT '优先级',
    MODIFY COLUMN STATE             VARCHAR(16)  NOT NULL COMMENT '状态',
    MODIFY COLUMN JOB_NAME          VARCHAR(190) NULL COMMENT 'Job 名称',
    MODIFY COLUMN JOB_GROUP         VARCHAR(190) NULL COMMENT 'Job 分组',
    MODIFY COLUMN IS_NONCONCURRENT  VARCHAR(1)   NULL COMMENT '是否禁止并发',
    MODIFY COLUMN REQUESTS_RECOVERY VARCHAR(1)   NULL COMMENT '是否请求恢复';

ALTER TABLE QRTZ_SCHEDULER_STATE COMMENT = 'Quartz：集群实例心跳状态';
ALTER TABLE QRTZ_SCHEDULER_STATE
    MODIFY COLUMN SCHED_NAME        VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN INSTANCE_NAME     VARCHAR(190) NOT NULL COMMENT '实例名称',
    MODIFY COLUMN LAST_CHECKIN_TIME BIGINT       NOT NULL COMMENT '最后签到时间（毫秒）',
    MODIFY COLUMN CHECKIN_INTERVAL  BIGINT       NOT NULL COMMENT '签到间隔（毫秒）';

ALTER TABLE QRTZ_LOCKS COMMENT = 'Quartz：集群悲观锁';
ALTER TABLE QRTZ_LOCKS
    MODIFY COLUMN SCHED_NAME VARCHAR(120) NOT NULL COMMENT '调度器名称',
    MODIFY COLUMN LOCK_NAME  VARCHAR(40)  NOT NULL COMMENT '锁名称';
