-- =============================================================================
-- 修复 Quartz 表名大小写 + 外键（Linux / lower_case_table_names=0）
-- =============================================================================
-- 适用现象：
--   1) Table 'xxx.QRTZ_JOB_DETAILS' doesn't exist（表是小写 qrtz_*）
--   2) FK fails ... REFERENCES `qrtz_triggers`（表已改大写，外键仍指向小写）
--
-- 本脚本会：
--   A. 若仍存在小写表则改名为大写
--   B. 删除并重建指向大写表的外键
--   C. 清空 QRTZ 运行时数据（sys_job 不受影响；应用重启后会从 sys_job 重新同步）
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------- A. 小写 → 大写（已是大写会报错，可整段注释掉）----------
-- RENAME TABLE
--   `qrtz_blob_triggers` TO `QRTZ_BLOB_TRIGGERS`,
--   `qrtz_calendars` TO `QRTZ_CALENDARS`,
--   `qrtz_cron_triggers` TO `QRTZ_CRON_TRIGGERS`,
--   `qrtz_fired_triggers` TO `QRTZ_FIRED_TRIGGERS`,
--   `qrtz_job_details` TO `QRTZ_JOB_DETAILS`,
--   `qrtz_locks` TO `QRTZ_LOCKS`,
--   `qrtz_paused_trigger_grps` TO `QRTZ_PAUSED_TRIGGER_GRPS`,
--   `qrtz_scheduler_state` TO `QRTZ_SCHEDULER_STATE`,
--   `qrtz_simple_triggers` TO `QRTZ_SIMPLE_TRIGGERS`,
--   `qrtz_simprop_triggers` TO `QRTZ_SIMPROP_TRIGGERS`,
--   `qrtz_triggers` TO `QRTZ_TRIGGERS`;

-- ---------- B. 卸掉旧外键（名字固定；不存在则忽略报错继续下一条）----------
ALTER TABLE `QRTZ_BLOB_TRIGGERS` DROP FOREIGN KEY `FK_QRTZ_BLOB_TRIGGERS`;
ALTER TABLE `QRTZ_CRON_TRIGGERS` DROP FOREIGN KEY `FK_QRTZ_CRON_TRIGGERS`;
ALTER TABLE `QRTZ_SIMPLE_TRIGGERS` DROP FOREIGN KEY `FK_QRTZ_SIMPLE_TRIGGERS`;
ALTER TABLE `QRTZ_SIMPROP_TRIGGERS` DROP FOREIGN KEY `FK_QRTZ_SIMPROP_TRIGGERS`;
ALTER TABLE `QRTZ_TRIGGERS` DROP FOREIGN KEY `FK_QRTZ_TRIGGERS_JOB`;

-- ---------- C. 清空调度运行时（保留锁表结构，重启后由应用重建 Job/Trigger）----------
TRUNCATE TABLE `QRTZ_BLOB_TRIGGERS`;
TRUNCATE TABLE `QRTZ_CRON_TRIGGERS`;
TRUNCATE TABLE `QRTZ_SIMPLE_TRIGGERS`;
TRUNCATE TABLE `QRTZ_SIMPROP_TRIGGERS`;
TRUNCATE TABLE `QRTZ_FIRED_TRIGGERS`;
TRUNCATE TABLE `QRTZ_PAUSED_TRIGGER_GRPS`;
TRUNCATE TABLE `QRTZ_TRIGGERS`;
TRUNCATE TABLE `QRTZ_JOB_DETAILS`;
TRUNCATE TABLE `QRTZ_SCHEDULER_STATE`;
TRUNCATE TABLE `QRTZ_LOCKS`;
TRUNCATE TABLE `QRTZ_CALENDARS`;

INSERT INTO `QRTZ_LOCKS` (`SCHED_NAME`, `LOCK_NAME`) VALUES
  ('omni-cluster', 'STATE_ACCESS'),
  ('omni-cluster', 'TRIGGER_ACCESS');

-- ---------- D. 按大写表名重建外键 ----------
ALTER TABLE `QRTZ_TRIGGERS`
  ADD CONSTRAINT `FK_QRTZ_TRIGGERS_JOB`
  FOREIGN KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`)
  REFERENCES `QRTZ_JOB_DETAILS` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`)
  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `QRTZ_CRON_TRIGGERS`
  ADD CONSTRAINT `FK_QRTZ_CRON_TRIGGERS`
  FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
  REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `QRTZ_SIMPLE_TRIGGERS`
  ADD CONSTRAINT `FK_QRTZ_SIMPLE_TRIGGERS`
  FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
  REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `QRTZ_SIMPROP_TRIGGERS`
  ADD CONSTRAINT `FK_QRTZ_SIMPROP_TRIGGERS`
  FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
  REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `QRTZ_BLOB_TRIGGERS`
  ADD CONSTRAINT `FK_QRTZ_BLOB_TRIGGERS`
  FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
  REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
  ON DELETE RESTRICT ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS = 1;

-- 校验外键是否指向大写表：
-- SELECT CONSTRAINT_NAME, TABLE_NAME, REFERENCED_TABLE_NAME
-- FROM information_schema.KEY_COLUMN_USAGE
-- WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_NAME LIKE 'QRTZ_%';
